# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_licorclient_wrappers", use_symbols = TRUE, package_name = "licorclient")

#' @usage NULL
#' @useDynLib licorclient, .registration = TRUE
NULL

#' Convert a LI-COR file to Parquet format
#' 
#' @param file Path to the input LI-COR file
#' @param output Path for the output Parquet file  
#' @param device Device type ("6800" or "6400")
#' @param config Measurement configuration ("standard", "fluorometer", "aquatic", "soil")
#' @export
convert <- function(file, output, device, config) .Call(wrap__convert, file, output, device, config)

#' Convert a LI-COR file directly to a data.frame or tibble
#'
#' @param file Path to the input LI-COR file
#' @param format Output format ("data.frame" or "tibble")
#' @param device Device type ("6800" or "6400") 
#' @param config Measurement configuration ("standard", "fluorometer", "aquatic", "soil")
#' @param preserve_names Whether to preserve original LI-COR variable names (TRUE) or convert to R-friendly names (FALSE)
#' @return data.frame or tibble with the converted data
#' @export
file_to_dataframe <- function(file, format, device, config, preserve_names) .Call(wrap__file_to_dataframe, file, format, device, config, preserve_names)


# nolint end
